"""Initial migration

Revision ID: 18aec3becb42
Revises: e7dbbb79938e
Create Date: 2024-12-12 09:51:13.062378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18aec3becb42'
down_revision: Union[str, None] = 'e7dbbb79938e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrow', 'return_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrow', 'return_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
