"""Initial migration

Revision ID: 48e8eac996d3
Revises: d9f77282e0b2
Create Date: 2024-12-10 09:15:20.478689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e8eac996d3'
down_revision: Union[str, None] = 'd9f77282e0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'book',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('book_title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.Column('available_copies', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
