"""update

Revision ID: e7dbbb79938e
Revises: 574112b533c1
Create Date: 2024-12-10 09:30:59.521804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7dbbb79938e'
down_revision: Union[str, None] = '574112b533c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('borrow', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrow', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('book', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
